version: "3.7"

networks:
  default:
    name: api-network

services:
  nginx:
    platform: linux/amd64
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile-local
      network: host
    ports:
      - 1337:80
    depends_on:
      - web
  web:
    platform: linux/amd64
    container_name: web
    restart: always
    build: 
      context: ./app
      dockerfile: Dockerfile-local
    command: uvicorn main:app --host 0.0.0.0 --reload
    env_file:
      - ".local.env"
    volumes:
      - ./app:/app
    depends_on:
      - db
  db:
    platform: linux/amd64
    image: postgres:14.4
    container_name: db
    restart: always
    ports:
      - 5432:5432
    env_file:
      - ".local.env"
    volumes:
      - /var/lib/docker/volumes/x-fit/postgres:/var/lib/postgresql/data
      




