version: "3.7"

networks:
  default:
    name: api-network

services:
  nginx:
    platform: linux/amd64
    container_name: nginx
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile-local
      network: host
    ports:
      - 1337:80
    depends_on:
      - web
  web:
    container_name: web
    restart: always
    build: 
      context: ./app
      dockerfile: Dockerfile-local
    command: uvicorn main:app --host 0.0.0.0 --reload
    env_file:
      - ".local.env"
    volumes:
      - ./app:/app
    depends_on:
      - db
  db:
    image: mysql:8.0.30
    container_name: db
    restart: always
    ports:
      - 3306:3306
    env_file:
      - ".local.env"
    volumes:
      - /var/lib/docker/volumes/x-fit/mysql:/var/lib/mysql




