"""220915_user

Revision ID: 0957a1c7ac76
Revises: f45d494f0d36
Create Date: 2022-09-15 17:39:19.406562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0957a1c7ac76'
down_revision = 'f45d494f0d36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('sex', sa.Enum('M', 'F'), nullable=True))
    op.add_column('users', sa.Column('height', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('weight', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('birth', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birth')
    op.drop_column('users', 'weight')
    op.drop_column('users', 'height')
    op.drop_column('users', 'sex')
    # ### end Alembic commands ###
