"""20221031 edit_wod_table

Revision ID: 2baec0edd8be
Revises: 982b140c6462
Create Date: 2022-10-31 13:19:12.993173

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2baec0edd8be'
down_revision = '982b140c6462'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wod_amrap_records', sa.Column('is_private', sa.Boolean(), nullable=True))
    op.add_column('wod_time_records', sa.Column('is_private', sa.Boolean(), nullable=True))
    op.drop_constraint('wods_ibfk_1', 'wods', type_='foreignkey')
    op.drop_column('wods', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('wods', sa.Column('user_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('wods_ibfk_1', 'wods', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_column('wod_time_records', 'is_private')
    op.drop_column('wod_amrap_records', 'is_private')
    # ### end Alembic commands ###
