"""220915_user

Revision ID: 69894a2e76af
Revises: 0957a1c7ac76
Create Date: 2022-09-15 22:33:25.040926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69894a2e76af'
down_revision = '0957a1c7ac76'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
