"""220916_user

Revision ID: ac519942a4fd
Revises: 69894a2e76af
Create Date: 2022-09-15 22:41:08.016281

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ac519942a4fd'
down_revision = '69894a2e76af'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('records_ibfk_1', 'records', type_='foreignkey')
    op.create_foreign_key(None, 'records', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'records', type_='foreignkey')
    op.create_foreign_key('records_ibfk_1', 'records', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
