# # pull official base image

FROM --platform=linux/amd64 python:3.10-slim-buster

# # set work directory

WORKDIR /app

# # set environment variables

ENV PYTHONPATH /app:$PYTHONPATH

# # upgrade pip
RUN pip install --upgrade pip


COPY ./requirements.txt ./
RUN pip install -r requirements.txt


# # copy project

COPY ./ /app/

# # run CMD

EXPOSE 8000

CMD ["alembic" , "--name", "dev_db", "upgrade", "head"]